### ISSUE TITLE
get actions instead of traces

### ISSUE THREAD

**Issue by dev-dantealighieri** [wharfkit/antelope#104]
i want to get only the actions created by the creator of the transaction but history api returns whole transaction to me, 

im using the following code snippet to get the transaction
```typescript
const transaction = await this.indexerRequest(
      EOS_INDEXER_API.V2.GET_TRANSACTION,
      {
        params: {
          id: transactionHash,
        },
        method: GET_METHOD,
      },
    );
```

[example transaction](https://bloks.io/transaction/3eae5fe9d49302fcc60957e1164510d1e47c4ed2922f5d859f71ca5607c7fd02)

for example in here, i want to only filter the following actions, not traces, which are
<img width="859" alt="image" src="https://github.com/eosrio/hyperion-history-api/assets/156019107/e537d4b3-99f8-4e9a-a9e5-592c9e87d811">

how to filter correctly? i tried to use creator_action_ordinal but thats not what i was looking for

thanks, Dante

**Comment by aaroncox** [comment]
I believe you want to filter the traces where the receiver is the account you're interested in. Without knowing more though its hard to tell. 

There was a conversation about 2 weeks ago in Telegram related to this:

https://t.me/antelopedevs/337237

I'd recommend bringing these kinds of questions up in Telegram, rather than here. This isn't a bug/issue with the Antelope library, but more of a question on understanding what the APIs are outputting and how to interpret it. You'll likely get faster responses as well 👍

**Comment by dev-dantealighieri** [comment]
i want to get only the actions created by creator of transaction, which is 5 in this case, all of them have `creator_action_ordinal` equal to 0 in the hyperion v1, but in the v2 they are not, that is weird, and i want to find a way to do the same that i can do in v1
